In [10]:
import pandas as pd
import os

In [12]:
screen_rpm_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/screen_rpm.csv")
screen_rpm_df.head()

,sgRNA_seq,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,HEL9217-311Cas9_RepA_p6_Avana-3,...,SCCH196-311Cas9-RepB-P6_Avana-4,SNU977-311Cas9-AVANA-RepA-p6_Avana-4,SNU977-311Cas9-AVANA-RepB-p6_Avana-4,HMMME-311cas9-RepA-p6_Avana-4,HMMME-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4
0,AAAAAAATCCAGCAATGCAG,10.960815,12.585414,11.318327,12.146607,13.270859,13.171601,10.048564,12.336110,11.567097,...,10.171232,8.889553,7.384747,8.341061,10.450371,11.749804,11.520618,7.935663,10.649346,11.246976
1,AAAAAACCCGTAGATAGCCT,13.493876,14.397133,12.793673,11.833550,11.143042,11.249908,10.236388,13.113188,13.676391,...,17.694478,11.744329,12.479451,20.146168,17.208278,10.370479,15.864909,11.109928,14.784035,12.524105
2,AAAAAAGAAGAAAAAACCAG,2.201632,1.908345,2.972712,3.819294,2.379795,1.801587,4.977326,5.730949,3.878380,...,2.227277,1.517729,2.830391,1.116699,1.207598,4.367862,1.237298,2.885696,3.005213,2.616055
3,AAAAAAGCTCAAGAAGGAGG,3.977142,3.623440,3.369074,4.194962,3.751677,6.445677,3.239958,5.099573,5.851590,...,4.256574,3.577503,3.808162,6.153241,4.760725,5.338498,2.722055,2.914553,4.376720,3.728393
4,AAAAAAGGCTGTAAAAGCGT,4.663673,6.377254,6.077545,4.226268,6.859410,5.164549,8.499019,5.828083,7.824801,...,5.518697,3.324548,5.506397,7.406679,8.174512,6.819995,5.416615,5.944533,7.644133,7.147803

In [14]:
screen_log2_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/screen_log2fc_vs_pdna.csv")

In [15]:
screen_log2_df.head(3)

,sgRNA_seq,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,HEL9217-311Cas9_RepA_p6_Avana-3,...,SCCH196-311Cas9-RepB-P6_Avana-4,SNU977-311Cas9-AVANA-RepA-p6_Avana-4,SNU977-311Cas9-AVANA-RepB-p6_Avana-4,HMMME-311cas9-RepA-p6_Avana-4,HMMME-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4
0,AAAAAAATCCAGCAATGCAG,-0.099109,0.084634,0.106890,0.200775,0.319156,0.309087,-0.050057,0.221422,0.135735,...,-0.197636,-0.373447,-0.611585,-0.455766,-0.162030,-0.006949,-0.033118,-0.519777,-0.137175,-0.064999
1,AAAAAACCCGTAGATAGCCT,-0.317544,-0.230326,-0.247926,-0.352012,-0.431802,-0.419161,-0.543754,-0.214888,-0.158435,...,0.049625,-0.503132,-0.422226,0.227409,0.011607,-0.667695,-0.098963,-0.576797,-0.194522,-0.417455
2,AAAAAAGAAGAAAAAACCAG,-0.254970,-0.393579,-0.130902,0.147795,-0.364091,-0.634782,0.458474,0.629783,0.165375,...,-0.243460,-0.601655,0.003714,-0.851961,-0.791300,0.490570,-0.772020,0.024395,0.068101,-0.079361

In [13]:
guide = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/raw/AvanaGuideMap.csv")
guide.head(3)

,sgRNA,GenomeAlignment,nAlignments,Gene,DropReason,UsedByChronos
0,AAAAAAATCCAGCAATGCAG,chr10_110964620_+,1.0,SHOC2 (8036),NaN,True
1,AAAAAACCCGTAGATAGCCT,chr12_95003615_+,1.0,NDUFA12 (55967),NaN,True
2,AAAAAAGAAGAAAAAACCAG,chr4_75970356_-,1.0,SDAD1 (55153),NaN,True

In [19]:
A = set(screen_log2_df['sgRNA_seq'])
B = set(guide['sgRNA'])

nol = B - A # nol = non_overlap
overlap = A & B # SequenceIDs that exist in BOTH screen_pass and raw
missing = A - B # missing = SequenceIDs that are in screen_pass but NOT in raw (Ideally len(missing) should be 0)

print(f"Non-overlapping SequenceIDs: {len(nol)}")
print(f"Overlapping SequenceIDs: {len(overlap)}")
print(f"Missing SequenceIDs: {len(missing)}")
mapping_rate = (len(overlap)) / (len(screen_log2_df))
print(f"Mapping rate: {mapping_rate:.2%}")

Non-overlapping SequenceIDs: 0
Overlapping SequenceIDs: 74687
Missing SequenceIDs: 0
Mapping rate: 100.00%

In [20]:
log2_gene_mapped_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/screen_log2fc_vs_pdna_gene_mapped.csv")
log2_gene_mapped_df.head(3)

,sgRNA_seq,gene,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,...,SCCH196-311Cas9-RepB-P6_Avana-4,SNU977-311Cas9-AVANA-RepA-p6_Avana-4,SNU977-311Cas9-AVANA-RepB-p6_Avana-4,HMMME-311cas9-RepA-p6_Avana-4,HMMME-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4
0,AAAAAAATCCAGCAATGCAG,SHOC2,-0.099109,0.084634,0.106890,0.200775,0.319156,0.309087,-0.050057,0.221422,...,-0.197636,-0.373447,-0.611585,-0.455766,-0.162030,-0.006949,-0.033118,-0.519777,-0.137175,-0.064999
1,AAAAAACCCGTAGATAGCCT,NDUFA12,-0.317544,-0.230326,-0.247926,-0.352012,-0.431802,-0.419161,-0.543754,-0.214888,...,0.049625,-0.503132,-0.422226,0.227409,0.011607,-0.667695,-0.098963,-0.576797,-0.194522,-0.417455
2,AAAAAAGAAGAAAAAACCAG,SDAD1,-0.254970,-0.393579,-0.130902,0.147795,-0.364091,-0.634782,0.458474,0.629783,...,-0.243460,-0.601655,0.003714,-0.851961,-0.791300,0.490570,-0.772020,0.024395,0.068101,-0.079361

In [21]:
unmapped_guides_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/unmapped_guides.csv")
unmapped_guides_df.head(3)

,sgRNA_seq,gene,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,...,SCCH196-311Cas9-RepB-P6_Avana-4,SNU977-311Cas9-AVANA-RepA-p6_Avana-4,SNU977-311Cas9-AVANA-RepB-p6_Avana-4,HMMME-311cas9-RepA-p6_Avana-4,HMMME-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4
0,AAAAACTCTGGGAAATGACT,NaN,0.363269,0.266652,0.233611,-0.165242,-0.126801,0.122999,0.452395,0.607153,...,-0.275664,-0.204977,0.050602,0.391665,0.563070,-0.193116,0.176149,0.301351,0.095816,-0.033208
1,AAAAAGCTTCCGCCTGATGG,NaN,0.119269,0.287082,0.227985,-0.064258,0.154939,-0.150369,0.066517,0.602185,...,0.603641,0.025481,-0.219661,0.677506,0.565881,0.142399,0.538397,0.292186,0.176461,0.101196
2,AAAAATCCTAAAATAAAATA,NaN,0.154863,0.345144,-0.376752,-0.181709,-0.324063,-0.338485,-0.038842,0.627039,...,0.393615,0.449702,-0.020826,0.793351,0.631534,0.186026,0.921508,0.037182,0.138792,-0.014936

In [22]:
gene_log2fc_feat_by_replicate_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/gene_level_log2fc_features_by_replicate.csv")
gene_log2fc_feat_by_replicate_df.head(3)

,gene,replicate_id,mean_log2fc,median_log2fc,min_log2fc,max_log2fc,std_log2fc,iqr_log2fc,n_guides,frac_guides_negative,frac_guides_strongly_negative
0,A1BG,Colo699-311cas9-RepA-p6_Avana-4,0.065034,0.076940,-0.177151,0.283407,0.188556,0.121516,4,0.25,0.0
1,A1CF,Colo699-311cas9-RepA-p6_Avana-4,0.094223,0.088642,-0.025452,0.225062,0.104451,0.099780,4,0.25,0.0
2,A2M,Colo699-311cas9-RepA-p6_Avana-4,0.101673,0.055304,-0.137908,0.433991,0.250519,0.277746,4,0.50,0.0

In [26]:
gene_aggregation_qc_df = pd.read_csv("/Volumes/nimas_usb/project_data_repo/crispr_ai_ml/data/processed/phase3_inputs/gene_level_aggregation_qc.csv")
print(gene_aggregation_qc_df.head(10))
print (f"Gene aggregation QC DataFrame shape: {gene_aggregation_qc_df.shape}")

                         metric       value
0                    input_rows     74687.0
1                 unique_sgrnas     74687.0
2                  unique_genes     17787.0
3             missing_gene_rows      4824.0
4             replicate_columns      2148.0
5           gene_replicate_rows  38206306.0
6        median_guides_per_gene         4.0
7           min_guides_per_gene         2.0
8           max_guides_per_gene        12.0
9  rows_with_less_than_3_guides    567772.0
Gene aggregation QC DataFrame shape: (38, 2)

In [29]:
print(gene_aggregation_qc_df[
    gene_aggregation_qc_df["metric"].isin([
        "median_guides_per_gene",
        "rows_with_less_than_3_guides",
        "missing_log2fc_rows_removed_total",
        "sample_mean_log2fc_median",
        "sample_std_log2fc_median"
    ])
])

#median_guides_per_gene
#rows_with_less_than_3_guides
#missing_log2fc_rows_removed_total
#sample_mean_log2fc_median
#sample_std_log2fc_median

                               metric         value
6              median_guides_per_gene  4.000000e+00
9        rows_with_less_than_3_guides  5.677720e+05
12  missing_log2fc_rows_removed_total  1.057158e+07
15          sample_mean_log2fc_median  4.451822e-03
25           sample_std_log2fc_median  2.994185e-01

In [39]:
less_than_3 = gene_aggregation_qc_df.loc[
    gene_aggregation_qc_df["metric"] == "rows_with_less_than_3_guides", 
    "value"
].iloc[0]

total_rows = gene_log2fc_feat_by_replicate_df.shape[0]

print(f"Rows with less than 3 guides: {less_than_3}")
print(f"Total rows in gene_log2fc_feat_by_replicate_df: {total_rows}")
print(f"Proportion of rows with less than 3 guides: {(less_than_3 / total_rows)*100:.2f}%")

Rows with less than 3 guides: 567772.0
Total rows in gene_log2fc_feat_by_replicate_df: 38206306
Proportion of rows with less than 3 guides: 1.49%